# Generated by Django 6.0.2 on 2026-04-18 13:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_full_name_remove_user_role_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_signature_path),
        ),
    ]
